name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: /amachlou/github-actions-dummy-standalone-action@v5

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

