name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: amachlou/github-actions-dummy-standalone-action@v1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

